---
  - hosts: all
    sudo: true
    pre_tasks:
      - name: Create a temporary directory for downloads
        file: path={{ download_dir }} owner={{ username }} group={{ username }} state=directory recurse=yes

      - name: Install apt packages
        apt: name={{ item }}
        with_items:
          - virtualenv
          - awscli
          - ruby-full

      - name: Install Python modules
        pip: name={{ item }}
        with_items:
          - boto
          - tox
          - virtualenv

      - name: Create a repositories directory
        file: path={{ repositories_dir }} owner={{ username }} group={{ username }} state=directory recurse=yes

    roles:
      - install-atom
      - install-java
      - install-scala
      - install-chrome
      - install-git
      - install-maven
      - install-eclipse
      - install-r
      - install-docker
      - install-shutter
      - install-zoom
      - install-packer
      - install-scala
      - install-sbt
      - configure-vim
      - configure-ssh

    post_tasks:
      - name: Delete the temporary downloads directory
        file: path={{ download_dir }} state=absent
