---
  - include_vars: github.yml

  - name: Create a temporary work directory
    file: path={{ user_home }}/ssh_tmp owner={{ username }} group={{ username }} state=directory recurse=yes

  - name: Create a directory for the key pair
    file: path={{ github_keys_dir }}/ owner={{ username }} group={{ username }} state=directory recurse=yes

  - name: Generate a new RSA key pair
    user:
      name: "{{ username }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: "{{ github_keys_dir }}/id_rsa"

  - name: Template the key request json
    template: src=github-request-body.json.j2 dest={{ user_home }}/ssh_tmp/github-request-body.json

  - name: Post the public key to Github
    uri:
      url: "{{ github_user_keys_url }}"
      method: POST
      body: "{{ lookup('file', user_home + '/ssh_tmp/github-request-body.json') }}"
      body_format: json
      status_code: 201
      headers:
        Authorization: "token {{ oauth_token }}"

  - name: Add an entry in the ssh config
    blockinfile:
      dest: "{{ ssh_config_file }}"
      marker: ""
      block: |
        # Github
        Host github.com
          HostName github.com
          IdentityFile {{ github_keys_dir }}/id_rsa
          User {{ github_username }}

  - name: Delete the temporary work directory
    file: path={{ user_home }}/ssh_tmp state=absent
