---
  - name: Download Packer
    get_url:
      url: "{{ packer_download_url }}"
      dest: "{{ download_dir }}/{{ packer_package_name }}"

  - name: Unzip the Packer archive
    unarchive:
      src: "{{ download_dir }}/{{ packer_package_name }}"
      dest: "{{ packer_install_path }}"
      remote_src: true
