---
  - name: Download the Atom deb package
    get_url:
      url: "{{ zoom_download_url }}"
      dest: "{{ download_dir }}/{{ zoom_download_name }}"

  - name: Install Zoom
    apt:
      deb: "{{ download_dir }}/{{ zoom_download_name }}"
