---
  - name: Check if Chrome is already installed
    command: dpkg-query -s google-chrome-stable
    register: chrome_installed_check
    failed_when: chrome_installed_check.rc > 1
    changed_when: chrome_installed_check.rc == 1
    
  - name: Download the Chrome deb package
    get_url:
      url: "{{ chrome_download_url }}"
      dest: "{{ download_dir }}/{{ chrome_package_name }}"
    when: chrome_installed_check.rc == 1

  - name: Install chrome
    shell: "dpkg -i {{ download_dir }}/{{ chrome_package_name }}"
    sudo: true
    ignore_errors: true
    register: chrome_install_result
    when: chrome_installed_check.rc == 1

  - include: update-and-retry.yml
    when: chrome_install_result is defined and chrome_install_result.failed
